"""create loans table

Revision ID: ac6ba97e0258
Revises: cbb63ae3881a
Create Date: 2026-10-08 17:01:58.901274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6ba97e0258'
down_revision: Union[str, Sequence[str], None] = 'cbb63ae3881a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=10), nullable=False))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_phone_number_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_unique_constraint(None, 'customers', ['phone'])
    op.drop_column('customers', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint(op.f('customers_phone_number_key'), 'customers', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
